#### K Fold Cross Validation
Evaluating Model Performance

#### option1: Use all avilable data for training and test on same datasets

In [1]:
#import the libraries (LogisticRegression, SVC and RandomForestClassifier)
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()

In [4]:
#using train and test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.3)

In [5]:
# creating logisticRegression Model
lr = LogisticRegression()

In [6]:
# train the model
lr.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [7]:
# evaluate the model score
lr.score(X_test,y_test)

0.9592592592592593

### SVM

In [8]:
# same problem with SVM
svm = SVC()

In [9]:
# train the model with training data
svm.fit(X_train, y_train)

SVC()

In [10]:
# find out the model score
svm.score(X_test,y_test)

0.987037037037037

## Random Forest Classifier

In [11]:
# create the random forest classifier with number of estimators are 40.
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

### K-Fold Cross Validation

In [12]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
#get score is a utility function and we can get our score while predicting the model
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [19]:
#LogisticRegression Score with this model
print("Logistic Regression Model Score" ,get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
print("SVC Model Score" ,get_score(SVC(),X_train,X_test,y_train,y_test))


Logistic Regression Model Score 0.9592592592592593
SVC Model Score 0.987037037037037


/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [23]:
print("Logistic Score:", scores_logistic)
print("Svm Score:", scores_svm)
print("RF Score:", scores_rf)

Logistic Score: [0.8948247078464107, 0.9532554257095158, 0.9098497495826378]
Svm Score: [0.3806343906510851, 0.41068447412353926, 0.5125208681135225]
RF Score: [0.9332220367278798, 0.9565943238731218, 0.9315525876460768]


### cross_val_score function


In [24]:
from sklearn.model_selection import cross_val_score

### Logistic regression model performance using cross_val_score

In [27]:
print("Logistic Score with cross validation score:", cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3))
print("SVC with cross validation score:", cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3))
print("Random Forest Classifier with cross validation score:", cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)
)

Logistic Score with cross validation score: [0.89482471 0.95325543 0.90984975]
SVC with cross validation score: [0.38063439 0.41068447 0.51252087]
Random Forest Classifier with cross validation score: [0.93489149 0.95158598 0.92654424]


### Parameter tunning using k fold cross validation

In [28]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.879258224705152

In [29]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.946576660459342

In [30]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9449006828057106

In [31]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9465859714463066

In [32]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=100),digits.data, digits.target, cv=10)
np.average(scores5)

0.9459993792675355

Exercise

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,


Logistic Regression

SVM

Decision Tree

Random Forest